### PR TITLE
Test read() and input()

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
Note these test outcomes are the same as existed before use of TextIOWrapper.
see https://travis-ci.org/jayvdb/stdio-mgr/builds/580618862

**Comment by jayvdb** [comment]
Also I am not sure about your preferred commit message structure - it would be a good thing to add to "CONTRIBUTING.md" or similar, if it doesnt already exist.

**Comment by jayvdb** [comment]
Apologies that I have added one Windows job to Travis.  It does slow down the CI considerably, but it means I encounter Windows problems on push instead of on PR, as Travis is most tightly integrated into my dev process (I've built tools on top of travispy, which I am supposed to be maintaining ..).

**Comment by bskinn** [comment]
> Also I am not sure about your preferred commit message structure - it would be a good thing to add to "CONTRIBUTING.md" or similar, if it doesnt already exist.

&lt;nod&gt; -- I'll add a bit about this when I draft it. I consider the leading allcaps tags as optional...once a branch is merged back in, I almost never look at them again. They just provide guidance when I'm looking back over a feature branch where I've added a whole bunch of not-necessarily-related stuff in one go.

Now that I'm not the only one working actively on `stdio-mgr`, I plan to use the feature-branch/PR/merge in a much more narrowly scoped fashion, to where the topics sort by PR rather than by commit callout.

**Comment by bskinn** [comment]
> Apologies that I have added one Windows job to Travis. It does slow down the CI considerably, but it means I encounter Windows problems on push instead of on PR, as Travis is most tightly integrated into my dev process (I've built tools on top of travispy, which I am supposed to be maintaining ..).

Is ok -- the test suite is small enough.

I'm interested to see that Travis has started adding new features now, post-sale. Maybe it won't stall out and die like so many predicted.

**Pull request merged**
